import type { Language } from '../context/LanguageContext'
import { useCallback } from 'react'

type DictValue = string | Record<string, string | Record<string, string>>
type Dict = Record<string, Record<string, DictValue>>

const dict: Record<Language, Dict> = {
  en: {
    nav: { home: 'Home', categories: 'Categories', practice: 'Practice', mistakes: 'Mistakes', review: 'Review', vocabulary: 'Vocabulary', results: 'Results', about: 'About' },
    brand: { title: 'Molecular Biology', subtitle: 'Molecular Biology · ZJU' },
    status: { answered: 'Answered', questions: 'Q', mistakes: 'Mistakes', vocab: 'Vocab' },
    tf: { correct: 'True', incorrect: 'False', correctMsg: '✓ Correct!', wrongMsg: '✗ Incorrect. Answer: ', explanation: 'Explanation' },
    mc: { noOptions: 'Options not generated. Answer: ', correct: '✓ Correct!', wrong: '✗ Incorrect. Answer: ', explanation: 'Explanation' },
    sa: { placeholder: 'Write your answer here (optional)...', reveal: 'Show Answer', reference: 'Reference Answer', gotIt: 'I got it right', gotWrong: 'I got it wrong', judgedCorrect: '✓ You marked yourself correct', judgedWrong: '✗ You marked yourself wrong. Added to mistakes.' },
    essay: { subtitle: 'Essay — draft your thoughts, then check the answer and self-judge', placeholder: 'Write your analysis here (optional)...' },
    tr: { zhToEn: 'Enter English translation (Enter submit, ←→ navigate, Space next, Tab speak)', enToZh: 'Enter Chinese translation', placeholderEn: 'Enter English translation...', placeholderZh: 'Enter Chinese translation...', submit: 'Submit', submitting: 'Submitting...', correct: '✓ Correct!', incorrect: '✗ Incorrect', correctAnswer: 'Correct answer:', acceptable: 'Acceptable answers:', yourAnswer: 'Your answer:', removeMistake: 'Remove from mistakes', removed: 'Removed from mistakes', next: 'Next →', nextSpace: 'Next (Space)' },
    flashcard: { noTerms: 'No terms', noTermsHint: 'Select translation subcategories first.', revealHint: 'Enter / Click to reveal', prev: '← Prev', show: 'Show (Enter)', hide: 'Hide', speak: 'Speak (Space)', next: 'Next →', shortcuts: 'Keys: ← Prev | → Next | Enter Toggle | Space Speak' },
    practice: { notFound: 'Question not found.', back: 'Back to categories', typeLabels: { translation: 'CN-EN Translation', 'true-false': 'True/False', 'multiple-choice': 'Multiple Choice', 'short-answer': 'Short Answer', essay: 'Essay' }, questionN: 'Q {n}/{m}', mistakeMode: 'Mistake Review', inMistakes: 'In mistakes', notInMistakes: 'Not in mistakes', removeMistake: 'Remove', addMistake: 'Add to mistakes', vocabOn: '✓ Vocab Pick ON', vocabOff: 'Vocab Pick Mode', vocabHint: 'Click English words to add to vocabulary', prev: '← Prev', next: 'Next →', results: 'View Results', restart: 'Restart' },
    intro: { title: 'ZJU Molecular Biology Exam Practice', subtitle: '213 exam questions covering 5 types across 10 categories', startBtn: 'Start Practice', resumeSession: 'Resume Session', mistakesBtn: 'Mistakes ({n})', totalQuestions: 'Total Questions', questionTypes: 'Question Types', subCategories: 'Subcategories', pendingMistakes: 'Pending Mistakes', typeStats: '{count} questions, {cats} subcategories', typeDesc: { translation: 'Abbreviation-tolerant matching', 'true-false': 'True/False with instant feedback', 'multiple-choice': '4 options with AI-generated explanations', 'short-answer': 'Self-assess after revealing answer', essay: 'Essay analysis with self-assessment' }, features: { types: { title: '5 Question Types', desc: 'Translation, True/False, Multiple Choice, Short Answer, Essay' }, mistakes: { title: 'Mistake Tracking', desc: 'Auto-collect wrong answers for targeted review' }, vocab: { title: 'Vocabulary Builder', desc: 'Click to collect English terms while practicing' }, flashcard: { title: 'Flashcard Review', desc: 'Chinese on front, English on back, Space to pronounce' }, selfJudge: { title: 'Self-Judge', desc: 'Open-ended questions: reveal answer, self-assess, optionally add to mistakes' } }, guideTitle: 'How to Use', step1Title: '1. Select Types', step1Desc: 'Pick question types and subcategories on the selection page', step2Title: '2. Answer Questions', step2Desc: 'Translate, judge true/false, pick options, or self-assess short answers', step3Title: '3. View Results', step3Desc: 'Check score breakdown with auto-graded vs self-graded stats', step4Title: '4. Review Mistakes', step4Desc: 'Wrong answers auto-collected for targeted drill practice', stats: { title: 'Your Stats', answered: 'Answered', mistakes: 'Mistakes', vocab: 'Vocab', accuracy: 'Accuracy' } },
    categories: { title: 'Select Types & Subcategories', subtitle: 'Choose subcategories to practice. {n} questions selected.', start: 'Start Practice ({n} Q)', startShort: 'Start Practice', review: 'Review Mode', selectAll: 'Select All', deselectAll: 'Deselect All', clear: 'Clear', questionCount: '{n}' },
    results: { title: 'Practice Results', accuracyLabel: 'Accuracy', accuracy: 'Accuracy: {n}%', answeredLabel: 'Answered', answered: 'Answered: {n}/{m}', correctLabel: 'Correct', correct: 'Correct: {n}', selfJudgedCorrect: 'Self-Judged Correct: {n}', selfJudgedWrong: 'Self-Judged Wrong: {n}', unansweredLabel: 'Unanswered', unanswered: 'Unanswered: {n}', totalLabel: 'Total Questions', byType: 'By Question Type', typeLabels: { translation: 'Translation', 'true-false': 'T/F', 'multiple-choice': 'MC', 'short-answer': 'SA', essay: 'Essay' }, scope: 'Practice Scope', retry: 'Try Again', backCategories: 'Back to Categories', reviewMistakes: 'Review Mistakes ({n})', viewMistakes: 'View Mistake Book' },
    mistakes: { title: 'Mistake Book', emptyTitle: 'No Mistakes', empty: 'No mistakes yet. Keep practicing!', emptyDesc: 'Wrong and self-judged-as-wrong answers will appear here.', emptyHint: 'Wrong answers and self-judged-as-wrong will appear here.', count: '{n} mistakes total.', hint: 'Click "Start Mistake Drill" for targeted review.', startDrill: 'Start Mistake Drill ({n} Q)', startDrillShort: 'Start Mistake Drill', clearAll: 'Clear All', confirmClear: 'Clear all {n} mistake records?', typeLabels: { translation: 'Translation', 'true-false': 'T/F', 'multiple-choice': 'MC', 'short-answer': 'SA', essay: 'Essay' }, wrongCount: '{n} wrong', yourAnswer: 'Your answer:', correctAnswer: 'Correct answer:', removeFromMistakes: 'Remove from mistakes' },
    vocab: { title: 'Vocabulary Book', empty: 'No vocabulary yet.', emptyTitle: 'No Vocabulary', emptyHint: 'Click English words during practice to add them.', emptyDesc: 'Enable vocab pick mode during practice and click English terms to add them.', subtitle: '{n} English terms collected via vocab pick mode.', export: 'Export', import: 'Import', clear: 'Clear', all: 'All', delete: 'Delete', statusLabels: { new: 'New', learning: 'Learning', mastered: 'Mastered' }, statusNew: 'New', statusLearning: 'Learning', statusMastered: 'Mastered', nextStatus: { new: '→ Learning', learning: '→ Mastered', mastered: '→ New' }, importError: 'Invalid file format' },
    review: { empty: 'No terms for review.', emptyHint: 'Select translation subcategories first.', noSelection: 'No Types Selected', noSelectionHint: 'Select subcategories containing translation questions first.', noTranslation: 'No Translation Questions', noTranslationHint: 'Selected subcategories have no translation questions. Select translation subcategories first.', goToCategories: 'Go to Category Selection' },
    about: { title: 'About', desc: 'ZJU Molecular Biology exam practice platform. 213 questions across 5 types. Blue color scheme. React 19 + Vite 8 + TypeScript 6. Pure static frontend, localStorage persistence. GitHub Pages deployment.', contentTitle: 'Content', source: 'Question Source', sourceDesc: 'Curated from past exam papers, organized by question type', types: 'Five Question Types', typesDesc: 'CN-EN Translation, True/False, Multiple Choice, Short Answer, Essay', abbreviation: 'Abbreviation Matching', abbreviationDesc: 'Translation accepts abbreviation-only answers (e.g. ChIP)', selfJudge: 'Self-Assessment', selfJudgeDesc: 'Short answer and essay questions are self-graded against reference answers', mistakes: 'Mistakes', mistakesDesc: 'Wrong answers auto-collected for targeted drill practice', vocab: 'Vocabulary', vocabDesc: 'Enable vocab pick mode to collect English terms from questions', techTitle: 'Technology', techDesc: 'React 19 + Vite 8 + TypeScript 6. Pure static frontend. All data stored in browser localStorage, nothing uploaded to any server.' },
    app: { loadingTitle: 'Molecular Biology Exam Bank', loading: 'Loading question bank...', errorTitle: 'Load Failed', errorMsg: 'Could not load question bank.', reload: 'Reload' },
  },
  zh: {
    nav: { home: '首页', categories: '题型选择', practice: '练习', mistakes: '错题本', review: '复习', vocabulary: '生词本', results: '结果', about: '关于' },
    brand: { title: '分子生物学习题库', subtitle: 'Molecular Biology · ZJU' },
    status: { answered: '已答', questions: '题', mistakes: '错题', vocab: '生词' },
    tf: { correct: '正确', incorrect: '错误', correctMsg: '✓ 回答正确！', wrongMsg: '✗ 回答错误，正确答案是：', explanation: '解析' },
    mc: { noOptions: '该题目的选项尚未生成。答案：', correct: '✓ 回答正确！', wrong: '✗ 回答错误，正确答案是：', explanation: '解析' },
    sa: { placeholder: '在此输入你的答案（可选，用于对照检查）...', reveal: '显示参考答案', reference: '参考答案', gotIt: '我基本答对了', gotWrong: '我答错了', judgedCorrect: '✓ 你判断自己回答正确', judgedWrong: '✗ 你判断自己回答错误，已加入错题本' },
    essay: { subtitle: '论述题 —— 请在草稿区写下你的思路，然后查看参考答案并自主判断', placeholder: '在此输入你的分析论述（可选）...' },
    tr: { zhToEn: '请输入英文翻译（Enter 提交，←→ 切题，Space 下一题，Tab 发音）', enToZh: '请输入中文翻译', placeholderEn: '输入英文翻译...', placeholderZh: '输入中文翻译...', submit: '提交', submitting: '提交中...', correct: '✓ 回答正确！', incorrect: '✗ 回答错误', correctAnswer: '正确答案：', acceptable: '可接受答案：', yourAnswer: '你的回答：', removeMistake: '不放入错题本', removed: '已从错题本移除', next: '下一题 →', nextSpace: '下一题 (Space)' },
    flashcard: { noTerms: '暂无复习词汇', noTermsHint: '请先在题型选择页勾选翻译子分类。', revealHint: '按 Enter / 点击卡片 显示英文翻译', prev: '← 上一个', show: '显示翻译 (Enter)', hide: '隐藏翻译', speak: '发音 (Space)', next: '下一个 →', shortcuts: '键盘快捷键：← 上一个 | → 下一个 | Enter 显示/隐藏翻译 | Space 发音' },
    practice: { notFound: '题库中找不到当前题目。', back: '返回题型选择', typeLabels: { translation: '中英名词互译', 'true-false': '判断题', 'multiple-choice': '选择题', 'short-answer': '简答题', essay: '分析论述题' }, questionN: '第 {n} / {m} 题', mistakeMode: '错题复习', inMistakes: '此题在错题本中', notInMistakes: '此题不在错题本中', removeMistake: '从错题本移除', addMistake: '加入错题本', vocabOn: '✓ 取词模式开', vocabOff: '生词取词模式', vocabHint: '点击题目中的英文单词即可收入生词本', prev: '上一题', next: '下一题', results: '查看结果', restart: '重新开始' },
    intro: { title: 'ZJU 分子生物学刷题工具', subtitle: '213 题，5 种题型，10 个分类', startBtn: '开始练习', resumeSession: '继续上次练习', mistakesBtn: '错题本（{n}）', totalQuestions: '总题量', questionTypes: '题型类别', subCategories: '子分类', pendingMistakes: '待复习错题', typeStats: '{count} 道题，{cats} 个子分类', typeDesc: { translation: '支持缩写匹配，仅答缩写即判对', 'true-false': '判断正误，即时反馈解析', 'multiple-choice': '四选一，含AI生成解析', 'short-answer': '自主作答后揭晓答案，自己判分', essay: '论述分析，揭晓答案后自主判分' }, features: { types: { title: '5 种题型', desc: '中英互译、判断、选择、简答、论述' }, mistakes: { title: '错题本', desc: '自动收录错题，支持专项复习' }, vocab: { title: '生词本', desc: '点击即可收集英文术语' }, flashcard: { title: '闪卡复习', desc: '正面中文，反面英文，空格发音' }, selfJudge: { title: '自主判断', desc: '开放题：查看答案、自主评估、可选加入错题本' } }, guideTitle: '使用指南', step1Title: '1. 选择题型', step1Desc: '在题型选择页勾选想要练习的题型和子分类', step2Title: '2. 答题练习', step2Desc: '按题型依次作答：输入翻译、判断正误、选择题选项、简答自主判分', step3Title: '3. 查看结果', step3Desc: '完成练习后查看成绩统计，区分自动判分与自主判分', step4Title: '4. 错题回顾', step4Desc: '错题自动收入错题本，支持错题专项练习', stats: { title: '你的统计', answered: '已答', mistakes: '错题', vocab: '生词', accuracy: '正确率' } },
    categories: { title: '选择题型与子分类', subtitle: '勾选想练习的子分类。已选 {n} 题。', start: '开始练习（{n} 题）', startShort: '开始练习', review: '复习模式', selectAll: '全选', deselectAll: '取消全选', clear: '清空', questionCount: '{n}' },
    results: { title: '练习结果', accuracyLabel: '正确率', accuracy: '正确率：{n}%', answeredLabel: '已作答', answered: '已答：{n}/{m}', correctLabel: '正确', correct: '正确：{n}', selfJudgedCorrect: '自判正确：{n}', selfJudgedWrong: '自判错误：{n}', unansweredLabel: '未作答', unanswered: '未答：{n}', totalLabel: '总题数', byType: '按题型统计', typeLabels: { translation: '名词互译', 'true-false': '判断', 'multiple-choice': '选择', 'short-answer': '简答', essay: '论述' }, scope: '本次练习范围', retry: '再做一次', backCategories: '返回题型选择', reviewMistakes: '复习错题（{n}）', viewMistakes: '查看错题本' },
    mistakes: { title: '错题本', emptyTitle: '错题本为空', empty: '暂无错题，继续练习吧！', emptyDesc: '完成练习后，答错的题目会自动加入错题本。简答题选择"我答错了"也会加入。', emptyHint: '答错或自判为错的题目会自动收录到这里。', count: '共 {n} 道错题。', hint: '点击"开始错题练习"进行针对性复习。', startDrill: '开始错题练习（{n} 题）', startDrillShort: '开始错题练习', clearAll: '清空全部', confirmClear: '确定清空 {n} 条错题记录？', typeLabels: { translation: '名词互译', 'true-false': '判断', 'multiple-choice': '选择', 'short-answer': '简答', essay: '论述' }, wrongCount: '错 {n} 次', yourAnswer: '你的答案：', correctAnswer: '正确答案：', removeFromMistakes: '从错题本移除' },
    vocab: { title: '生词本', empty: '暂无生词。', emptyTitle: '暂无生词', emptyHint: '练习时点击英文单词即可收入。', emptyDesc: '在练习页开启取词模式，点击题目中的英文术语即可添加到生词本。', subtitle: '练习中通过取词模式收集的英文术语，共 {n} 个。', export: '导出', import: '导入', clear: '清空', all: '全部', delete: '删除', statusLabels: { new: '新词', learning: '学习中', mastered: '已掌握' }, statusNew: '新', statusLearning: '学习中', statusMastered: '已掌握', nextStatus: { new: '→ 学习中', learning: '→ 已掌握', mastered: '→ 新词' }, importError: '文件格式不正确' },
    review: { empty: '暂无复习词汇。', emptyHint: '请先在题型选择页勾选翻译子分类。', noSelection: '未选择题型', noSelectionHint: '请先在题型选择页勾选包含翻译题的子分类。', noTranslation: '没有翻译题', noTranslationHint: '当前选中的子分类中不包含中英名词互译题。请在题型选择页勾选翻译题子分类后再试。', goToCategories: '前往题型选择' },
    about: { title: '关于', desc: 'ZJU 分子生物学刷题工具。213 题，5 种题型。蓝色配色。React 19 + Vite 8 + TypeScript 6。纯静态前端，localStorage 持久化。GitHub Pages 部署。', contentTitle: '内容说明', source: '题库来源', sourceDesc: '历年考试真题汇总，按题型分类整理', types: '五大题型', typesDesc: '中英名词互译、判断题、选择题、简答题、分析论述题', abbreviation: '缩写匹配', abbreviationDesc: '中英互译题支持仅答缩写（如 ChIP）即判对', selfJudge: '自主判分', selfJudgeDesc: '简答题与论述题不自动判分，由你对照参考答案自行判断', mistakes: '错题本', mistakesDesc: '答错的题目自动收入错题本，支持错题专项练习', vocab: '生词本', vocabDesc: '开启取词模式后可点击题目中英文术语收入生词本', techTitle: '技术实现', techDesc: 'React 19 + Vite 8 + TypeScript 6，纯静态前端应用。所有练习数据仅存储在浏览器本地（localStorage），不上传任何服务器。' },
    app: { loadingTitle: '分子生物学习题库', loading: '正在加载题库...', errorTitle: '题库加载失败', errorMsg: '无法加载题库数据。', reload: '重新加载' },
  },
}

export function useT() {
  // UI labels always use Chinese regardless of content language
  const zh = dict.zh
  return useCallback((category: string, key: string): string => {
    const parts = category.split('.')
    let node: unknown = zh
    for (const part of parts) {
      if (node == null || typeof node !== 'object') return key
      node = (node as Record<string, unknown>)[part]
    }
    if (node != null && typeof node === 'object' && !Array.isArray(node)) {
      return (node as Record<string, unknown>)[key] as string ?? key
    }
    return key
  }, [])
}
